[config]
all_langs = [
    "af",
    "sq",
    "als",
    "am",
    "ar",
    "an",
    "hy",
    "as",
    "ast",
    "az",
    "ba",
    "eu",
    "bar",
    "be",
    "bn",
    "bh",
    "bpy",
    "bs",
    "br",
    "bg",
    "my",
    "ca",
    "ceb",
    "bcl",
    "ce",
    "zh",
    "cv",
    "co",
    "hr",
    "cs",
    "da",
    "dv",
    "nl",
    "pa",
    "arz",
    "eml",
    "en",
    "myv",
    "eo",
    "et",
    "hif",
    "fi",
    "fr",
    "gl",
    "ka",
    "de",
    "gom",
    "el",
    "gu",
    "ht",
    "he",
    "mrj",
    "hi",
    "hu",
    "is",
    "io",
    "ilo",
    "id",
    "ia",
    "ga",
    "it",
    "ja",
    "jv",
    "kn",
    "pam",
    "kk",
    "km",
    "ky",
    "ko",
    "ku",
    "ckb",
    "la",
    "lv",
    "li",
    "lt",
    "lmo",
    "nds",
    "lb",
    "mk",
    "mai",
    "mg",
    "ms",
    "ml",
    "mt",
    "gv",
    "mr",
    "mzn",
    "mhr",
    "min",
    "xmf",
    "mwl",
    "mn",
    "nah",
    "nap",
    "ne",
    "new",
    "frr",
    "nso",
    "no",
    "nn",
    "oc",
    "or",
    "os",
    "pfl",
    "ps",
    "fa",
    "pms",
    "pl",
    "pt",
    "qu",
    "ro",
    "rm",
    "ru",
    "sah",
    "sa",
    "sc",
    "sco",
    "gd",
    "sr",
    "sh",
    "scn",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "azb",
    "es",
    "su",
    "sw",
    "sv",
    "tl",
    "tg",
    "ta",
    "tt",
    "te",
    "th",
    "bo",
    "tr",
    "tk",
    "uk",
    "hsb",
    "ur",
    "ug",
    "uz",
    "vec",
    "vi",
    "vo",
    "wa",
    "war",
    "cy",
    "vls",
    "fy",
    "pnb",
    "yi",
    "yo",
    "diq",
    "zea",
]
langs = ["en"]
